### ISSUE TITLE
Build with mod_brotli

### ISSUE THREAD

**Issue by dotsam** [iusrepo/httpd24u#27]
mod_brotli has been in stable since 2.4.26, and fedora has been building with it since 2.4.29-2, can we build it here as well?

I suppose this is also a new package request for the brotli library too... or see if the fedora maintainer will maintain it for EPEL too... https://apps.fedoraproject.org/packages/brotli

Let me know your thoughts on this, if you'd like me to reach out to the brotli maintainer.

**Comment by carlwgeorge** [comment]
You are correct that this will add a [build requirement on brotli-devel](https://src.fedoraproject.org/rpms/httpd/c/95a0c9518b8a5659e7ba07aad0bcc338409e86cf).  Unfortunately the Fedora maintainer has [already refused to add it to EPEL 7](https://bugzilla.redhat.com/show_bug.cgi?id=1611831), and one can assume his stance will be the same for EPEL 6.  It is possible he would be willing to take on a co-maintainer to maintain the EPEL branches.  I have requested that in bugzilla.

**Comment by dotsam** [comment]
Looks like brotli and brotli-devel has landed in EPEL stable, can you add this to the spec now? Thanks!

**Comment by carlwgeorge** [comment]
Thanks for the reminder.  I've enabled mod_brotli in the EL7 build.  httpd24u-2.4.39-2 is now available from ius-testing on the new [IUS CDN](https://github.com/iusrepo/infrastructure/issues/14).  Please try it out and share your feedback.

**Comment by dotsam** [comment]
Perfect, thanks! Installed and confirmed working now, will monitor and report back if there are any issues.

**Comment by carlwgeorge** [comment]
How is this package working for you?

**Comment by dotsam** [comment]
No issues, everything looks good

**Comment by carlwgeorge** [comment]
Thanks for testing, I've pushed it to stable.
