### ISSUE TITLE
Revisit building mod_md

### ISSUE THREAD

**Issue by orenwolf** [iusrepo/httpd24u#33]
#17 was closed due to the build requiring a different curl version.

However, RHSCL ships httpd24-curl that takes care of this limitation.

Given that mod_md is going to be a default module in the next version of apache, I'd like to see if there's a way to have this decision revisited. Specifically, the next httpd release will move this module out of "Experimental" status, and into the base, so you will have to *actively disable mod_md* in your builds going forward if you choose not to support it.

Perhaps you can have a look at how softwarecollections.org handles this situation and see if there's a way forward here?

**Comment by carlwgeorge** [comment]
SCL handles this by building an SCL-style parallel installed version of curl.  The specifics of this implementation means it only works for other packages in the collection.  IUS packages aren't SCLs, so we can't use that directly or even do something similar.

In theory one could create a typical compat-style parallel installable newer curl package, but such a thing would be best suited for EPEL.  As I said before in #17, IUS is not interested on taking on the maintenance workload of such a thing.  If someone else ships it in EPEL, or if RHEL decide to include it, we can revisit this.
