### ISSUE TITLE
Update to 2.4.46 For security Issues

### ISSUE THREAD

**Issue by SteveSimpson** [iusrepo/httpd24u#37]
Multiple CVE's fixed - see https://downloads.apache.org/httpd/CHANGES_2.4.46

**Comment by SteveSimpson** [comment]
Pull request for -1 is in. With -2, built agains OpenSSL 1.1 and TLS 1.3. Shortly to follow.

**Comment by carlwgeorge** [comment]
With #38 merged, httpd24u-2.4.46-1.el6.ius and httpd24u-2.4.46-1.el7.ius have been published to the testing repos.  If anyone gets a change to test them, share your feedback here and we'll promote them to the main repos.

**Comment by SteveSimpson** [comment]
My test servers have been running for a couple of days now with no problems.

**Comment by carlwgeorge** [comment]
Thanks for the testing feedback.  I've promoted those builds to the main repos.
