### ISSUE TITLE
Missing httpd24u 2.4.52 release in main ius repository

### ISSUE THREAD

**Issue by reporter4u** [iusrepo/httpd24u#50]
As long as reported in ius [faq](https://ius.io/faq#how-long-do-updates-have-to-wait-in-the-testing-repository-before-being-promoted-to-the-main-repository), is it possible to promote form ius-testing the latest 2.4.52 release into the main ius repository?

Thank you.

Roberto

**Comment by reporter4u** [comment]
Someone promotes it.

Thank you.

**Comment by reporter4u** [comment]
Why no one is promoting this package?

**Comment by jeffsheltren** [comment]
> Why no one is promoting this package?

This is a volunteer effort.

This package has been pushed to the main IUS repo.
