### ISSUE TITLE
/etc/httpd/conf/magic broken since version 2.4.54-1

### ISSUE THREAD

**Issue by sebastianhalles** [iusrepo/httpd24u#55]
Since update to Version 2.4.54-1 Apache shows the following error during restart in error.log:
- [Thu Jul 07 16:48:00.516980 2022] [mime_magic:error] [pid 17174] AH01521: mod_mime_magic: offset AddIconByType /icons/bomb.gif application/x-coredump invalid
- [Thu Jul 07 16:48:00.517065 2022] [mime_magic:error] [pid 17174] AH01524: mod_mime_magic: type AddIconByType /icons/bomb.gif application/x-coredump invalid

The error is caused by line 386 in /etc/httpd/conf/magic. (AddIconByType /icons/bomb.gif application/x-coredump)

The wrong line was added with httpd-2.4.53-icons.patch in line 38.

**Comment by carlwgeorge** [comment]
Fixed by #56.
