### ISSUE TITLE
update to 2.4.55

### ISSUE THREAD

**Issue by msnitish** [iusrepo/httpd24u#59]
Can I use this rpm file to update my current version of httpd ?
current version : 2.4.6 (downloaded using centos 7 base/updates yum repo)
Steps I thought of : 
1. download the rpm file using the mirror URL 
2. yum localinstall <httpd.*.rpm>

Will these correctly update all the httpd files ?

**Comment by carlwgeorge** [comment]
Downloading and installing a single RPM is not recommended.  You would also have to download the dependencies, and even if you do that it puts you in a situation where you don't get further updates to the package.  Please see the setup instructions on our website for how to configure the IUS yum repo.

https://ius.io/setup

Once you have the repo configured, you can use httpd24u as an upgrade over the stock httpd, but it doesn't happen automatically.  See the usage instructions on our website for how to correctly update.

https://ius.io/usage
