### ISSUE TITLE
httpd-2.4.56

### ISSUE THREAD

**Issue by k-ku-ma** [iusrepo/httpd24u#61]
**What new package do you want?**

httpd-2.4.56

**Why?**

Security Issues in the current 2.4.55

**Testing**

I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
Fixed in #60.
